In [62]:
from bs4 import BeautifulSoup
import requests

url = BeautifulSoup('https://www.doed.gov.np/license/54','html.parser')
response = requests.get(url)
data = response.text
soup = BeautifulSoup(data,'lxml')
tags = soup.table
tag = tags.find_all('tr')
a = []
for i in tag:
    s=i.get_text()
    a.append(s)
final = a[1:]
final_data = []
for i in final:
    f= i.split('\n')
    final_data.append(f)
header = [['Sn','Project','Capacity(MW)','River','LicNo','IssueData','Validity','Promoter','Address','Latitude N','Longitude E','VDC/District','COD']]    
output_data = header + final_data

C:\Users\Dell\anaconda3\lib\site-packages\bs4\__init__.py:389: UserWarning: "https://www.doed.gov.np/license/54" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

In [63]:
import csv

f = open('hydropower.csv','w')
write = csv.writer(f)
for i in output_data:
    write.writerow(i)
f.close()

In [64]:
import pandas as pd
df = pd.read_csv('hydropower.csv')
df

,Unnamed: 0,1,Khimti -I,60.000,Khimti Khola,1.1,2051-11-01,2101-10-29,Himal Power Limited,,"27o 28' 28""","27o 33' 07""","86o 06' 04""","86o 15' 00""","Sahure, Hawa (Dolakha) Betali (Ramechhap)",2057-03-27,COD 2000-07-11,Unnamed: 17
0,NaN,2.0,Sun Koshi,10.050,Sun Koshi,1_gtd,2051-12-06,2101-11-30,Nepal Electricity Authority,,"27o 45' 00""","27o 46' 00""","85o 50' 10""","85o 52' 30""",(Sindhupalchok),2029-01-01,COD 1972,NaN
1,NaN,3.0,Tinau,1.024,Tinau,1_gtd,2051-12-06,2101-11-30,Nepal Electricity Authority,,"27o 43' 00""","27o 44' 20""","83o 27' 30""","83o 28' 00""",(Palpa),2038-01-01,COD,NaN
2,NaN,4.0,Seti,1.500,Seti Khola,1_gtd,2051-12-06,2101-11-30,Nepal Electricity Authority,,"28o 13' 50""","28o 15' 06""","83o 57' 54""","83o 59' 34""",(Kaski),2042-07-16,COD 1985-11-01,NaN
3,NaN,5.0,Marsyangdi,69.000,Marsyangdi,1_gtd,2051-12-06,2101-11-30,Nepal Electricity Authority,,"27o 52' 25""","27o 56' 53""","84o 25' 40""","84o 32' 42""",(Tanahu),2046-07-20,COD 1989-11-05,NaN
4,NaN,6.0,Kulekhani-I,60.000,Kulekhani,1_gtd,2051-12-06,2101-11-30,Nepal Electricity Authority,,"27o 32' 06""","27o 37' 48""","85o 08' 21""","85o 10' 50""",(Makawanpur),2039-01-21,Storage Project COD 1982-05-14,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,NaN,95.0,Rudi Khola-B Hydropower Project,6.600,Rudi Khola,199,2074-02-26,2109-02-25,Bindhyabasini Hydropower Development Co. Pvt Ltd,"Naya Baneshwor, Kathmandu, P.O. Box no 10242...","28o 16' 39""","28o 17' 50""","84o 11' 00""","84o 13' 00""",Mijuredada (Kaski) Pasagaun (Lamjung),2076-11-05,Survey Lic No: 646 Date: 2069-09-26 difference...,NaN
94,NaN,96.0,Padam Khola SHP,4.800,Padam Khola,207,2074-06-29,2109-06-28,Dolti Power Company P. Ltd,"Baneshwor, Kathmandu, Phone no 4105021, 975...","28o 54' 02""","28o 55' 00""","81o 49' 22""","81o 51' 19""",Kalika (Dailekh),2076-09-08,Survey Lic No: 684 Date: 2071-05-29 (Commercia...,NaN
95,NaN,97.0,Super Mai-A HPP,9.600,Mai Khola,224,2074-11-18,2109-11-17,Sagarmatha Jalbidhyut Company P.Ltd.,"168/22 Thapa Gaun, New Banesor-10, Kathmandu...","26o 58' 08""","26o 59' 59""","87o 57' 36""","87o 58' 26""","Sumbek, Sulubung, Pyang (Ilam)",2077-02-32,Survey Lic No: 712 Date: 2072-09-30,NaN
96,NaN,98.0,Super Mai Khola Cascade HPP,3.000,Mai Khola,250,2075-11-05,2110-11-04,Mai Khola Hydropower Pvt.Ltd.,"Kathmandu-10, Thapagaun; 01-4227294, 4468423...","26o 55' 41""","26o 56' 27""","87o 56' 34""","87o 57' 13""","Soyang, Barbote (Ilam)",2077-03-31,Survey Lic No: 755 Date: 2073-08-09; Ilam Na P...,NaN
97,sn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN